import { d3, d6 } from '../../../controllers/util';
import { IUnit } from '../../interfaces';


export const ContemptorMortis: IUnit = {
    name: 'Contemptor Mortis Dreadnaughts',
    description: 'with 2 Twin Heavy Bolters and Cyclone Missile Launcher',
    points: 160,
    tags: ['vehicle'],
    modelCountPerUnit: 1,
    toHit: 2,
    balisticSkill: 3,
    weapons: [
        {
            name: 'Two Twin Heavy Bolters',
            type: 'Heavy',
            numberOfShotsLabel: '12',
            tags: ['bolter', 'multiprofile'],
            uniqueIdentifier: 'loadout',
            numberOfShots: () => 12,
            AP: 1,
            strength: 5,
            damage: () => 1,
        },
        {
            name: 'Two Twin Lascannons',
            type: 'Heavy',
            numberOfShotsLabel: '4',
            tags: ['multiprofile'],
            uniqueIdentifier: 'loadout',
            numberOfShots: () => 4,
            AP: 3,
            strength: 9,
            damage: () => d6(),
        },
        {
            name: 'Two Kheres Assault Cannons',
            type: 'Heavy',
            numberOfShotsLabel: '12',
            tags: ['multiprofile'],
            uniqueIdentifier: 'loadout',
            numberOfShots: () => 12,
            AP: 1,
            strength: 7,
            damage: () => 1,
        },
        {
            name: 'Two Plasma Cannons (overcharged)',
            type: 'Heavy',
            numberOfShotsLabel: '2d3',
            tags: ['multiprofile'],
            uniqueIdentifier: 'loadout',
            numberOfShots: () => (d3() + d3()),
            AP: 3,
            strength: 8,
            damage: () => 2,
        },
        {
            name: 'Two Plasma Cannons',
            type: 'Heavy',
            numberOfShotsLabel: '2d3',
            tags: ['multiprofile'],
            uniqueIdentifier: 'loadout',
            numberOfShots: () => (d3() + d3()),
            AP: 3,
            strength: 7,
            damage: () => 1,
        },
        {
            name: 'Two Twin Autocannons Cannons',
            type: 'Heavy',
            numberOfShotsLabel: '8',
            tags: ['multiprofile'],
            uniqueIdentifier: 'loadout',
            numberOfShots: () => 8,
            AP: 1,
            strength: 7,
            damage: () => 2,
        },
        {
            name: 'Two Multi Meltas',
            type: 'Heavy',
            numberOfShotsLabel: '2',
            tags: ['multiprofile'],
            uniqueIdentifier: 'loadout',
            numberOfShots: () => 2,
            AP: 4,
            strength: 7,
            damage: () => {
                const roll = d6();
                const reroll = d6();
                return roll > reroll ? roll : reroll;
            },
        },
        {
            name: 'Cyclone Missile - Frag',
            type: 'Heavy',
            tags: ['multiprofile', 'cyclone missile'],
            uniqueIdentifier: 'cyclone missile',
            numberOfShotsLabel: '2d3',
            numberOfShots: () => (d3() + d3()),
            AP: 0,
            strength: 4,
            damage: () => 1,
        },
        {
            name: 'Cyclone Missile - Krak',
            type: 'Heavy',
            tags: ['multiprofile', 'cyclone missile'],
            uniqueIdentifier: 'cyclone missile',
            numberOfShotsLabel: '2',
            numberOfShots: () => 2,
            AP: 2,
            strength: 8,
            damage: () => d6(),
        }
    ]
};
