import { d3, d6 } from '../../../controllers/util';
import { IUnit } from '../../interfaces';


export const Devastators: IUnit = {
    name: 'Devastators (whole unit)',
    description: '',
    points: 150,
    tags: ['infantry'],
    weaponSkill: 3,
    modelCountPerUnit: 5,
    balisticSkill: 3,
    weapons: [
        {
            name: 'Lascannons',
            type: 'Heavy',
            numberOfShotsLabel: '1',
            tags: ['multiprofile'],
            uniqueIdentifier: 'heavyweapon',
            numberOfShots: () => 1,
            AP: 3,
            strength: 9,
            damage: () => d6(),
        },
        {
            name: 'Missile Launchers (Krak)',
            type: 'Heavy',
            numberOfShotsLabel: '1',
            tags: ['multiprofile'],
            uniqueIdentifier: 'heavyweapon',
            numberOfShots: () => 1,
            AP: 2,
            strength: 8,
            damage: () => d6(),
        },
        {
            name: 'Missile Launchers (Frag)',
            type: 'Heavy',
            numberOfShotsLabel: 'd6',
            tags: ['multiprofile'],
            uniqueIdentifier: 'heavyweapon',
            numberOfShots: () => d6(),
            AP: 0,
            strength: 4,
            damage: () => 1,
        },
        {
            name: 'Heavy Bolters',
            type: 'Heavy',
            numberOfShotsLabel: '3',
            tags: ['bolter', 'multiprofile'],
            uniqueIdentifier: 'heavyweapon',
            numberOfShots: () => 3,
            AP: 1,
            strength: 5,
            damage: () => 1,
        },
        {
            name: '4 Grav Cannons (set to d3 wounds)',
            type: 'Heavy',
            numberOfShotsLabel: '4',
            tags: ['multiprofile'],
            uniqueIdentifier: 'heavyweapon',
            numberOfShots: () => 4,
            AP: 3,
            strength: 5,
            damage: () => d3(),
        },
        {
            name: 'Multi Meltas (assumed close)',
            type: 'Heavy',
            numberOfShotsLabel: '1',
            tags: ['multiprofile'],
            uniqueIdentifier: 'heavyweapon',
            numberOfShots: () => 1,
            AP: 4,
            strength: 8,
            damage: () => {
                const roll = d6();
                const roll2 = d6();
                if (roll > roll2) return roll;
                return roll2;
            },
        },
        {
            name: 'Plasma Cannons (regular)',
            type: 'Heavy',
            numberOfShotsLabel: 'd3',
            tags: ['multiprofile'],
            uniqueIdentifier: 'heavyweapon',
            numberOfShots: () => d3(),
            AP: 3,
            strength: 7,
            damage: () => 1,
        },
        {
            name: '4 Plasma Cannons',
            type: 'Heavy',
            numberOfShotsLabel: 'd3',
            tags: ['multiprofile'],
            uniqueIdentifier: 'heavyweapon',
            numberOfShots: () => d3(),
            AP: 3,
            strength: 8,
            damage: () => 2,
        },
        /* plus one to hit option */
        {
            name: 'Lascannons +1 to hit',
            type: 'Heavy',
            numberOfShotsLabel: '1',
            tags: ['multiprofile'],
            uniqueIdentifier: 'heavyweapon',
            numberOfShots: () => 1,
            AP: 3,
            strength: 9,
            damage: () => d6(),
            plusToHit: 1,
        },
        {
            name: 'Missile Launchers (Krak) +1 to hit',
            type: 'Heavy',
            numberOfShotsLabel: '1',
            tags: ['multiprofile'],
            uniqueIdentifier: 'heavyweapon',
            numberOfShots: () => 1,
            AP: 2,
            strength: 8,
            damage: () => d6(),
            plusToHit: 1,
        },
        {
            name: 'Missile Launchers (Frag) +1 to hit',
            type: 'Heavy',
            numberOfShotsLabel: 'd6',
            tags: ['multiprofile'],
            uniqueIdentifier: 'heavyweapon',
            numberOfShots: () => d6(),
            AP: 0,
            strength: 4,
            damage: () => 1,
            plusToHit: 1,
        },
        {
            name: 'Heavy Bolters +1 to hit',
            type: 'Heavy',
            numberOfShotsLabel: '3',
            tags: ['bolter', 'multiprofile'],
            uniqueIdentifier: 'heavyweapon',
            numberOfShots: () => 3,
            AP: 1,
            strength: 5,
            damage: () => 1,
            plusToHit: 1,
        },
        {
            name: '4 Grav Cannons (set to d3 wounds) +1 to hit',
            type: 'Heavy',
            numberOfShotsLabel: '4',
            tags: ['multiprofile'],
            uniqueIdentifier: 'heavyweapon',
            numberOfShots: () => 4,
            AP: 3,
            strength: 5,
            damage: () => d3(),
            plusToHit: 1,
        },
        {
            name: 'Multi Meltas (assumed close) +1 to hit',
            type: 'Heavy',
            numberOfShotsLabel: '1',
            tags: ['multiprofile'],
            uniqueIdentifier: 'heavyweapon',
            numberOfShots: () => 1,
            AP: 4,
            strength: 8,
            damage: () => {
                const roll = d6();
                const roll2 = d6();
                if (roll > roll2) return roll;
                return roll2;
            },
            plusToHit: 1,
        },

        {
            name: 'Plasma Cannons (regular) +1 to hit',
            type: 'Heavy',
            numberOfShotsLabel: 'd3',
            tags: ['multiprofile'],
            uniqueIdentifier: 'heavyweapon',
            numberOfShots: () => d3(),
            AP: 3,
            strength: 7,
            damage: () => 1,
            plusToHit: 1,
        },
        {
            name: 'Plasma Cannons (overcharged) +1 to hit',
            type: 'Heavy',
            numberOfShotsLabel: 'd3',
            tags: ['multiprofile'],
            uniqueIdentifier: 'heavyweapon',
            numberOfShots: () => d3(),
            AP: 3,
            strength: 8,
            damage: () => 2,
            plusToHit: 1,
        },
    ]
};
