import { d3 } from '../../../controllers/util';
import { IUnit } from '../../interfaces';


export const Elminators: IUnit = {
    name: 'Eliminators (whole unit)',
    description: '',
    points: 74,
    tags: ['infantry'],
    toHit: 3,
    modelCountPerUnit: 3,
    balisticSkill: 3,
    weapons: [
        {
            name: 'Sniper Executioner Round',
            type: 'Heavy',
            numberOfShotsLabel: '1 (x3)',
            tags: ['bolter', 'multiprofile'],
            uniqueIdentifier: 'sniper',
            numberOfShots: () => 3,
            AP: 1,
            plusToHit: 2,
            strength: 5,
            damage: () => 1,
        },
        {
            name: 'Sniper Hyperfrag Round',
            type: 'Heavy',
            numberOfShotsLabel: 'd3 (x3)',
            tags: ['multiprofile', 'bolter'],
            uniqueIdentifier: 'sniper',
            numberOfShots: () => d3() + d3() + d3(),
            AP: 0,
            strength: 5,
            damage: () => 1,
        },
        {
            name: 'Sniper Mortis Round',
            type: 'Heavy',
            numberOfShotsLabel: '1 (x3)',
            tags: ['multiprofile', 'bolter', 'mortal wound on 6+s to wound'],
            uniqueIdentifier: 'sniper',
            numberOfShots: () => 3,
            AP: 2,
            strength: 5,
            damage: () => d3(),
        },
        {
            name: 'Sniper Executioner Round (seargeant buffs)',
            type: 'Heavy',
            numberOfShotsLabel: '1 (x2)',
            tags: ['bolter', 'multiprofile'],
            uniqueIdentifier: 'sniper',
            numberOfShots: () => 2,
            AP: 1,
            plusToWound: 1,
            plusToHit: 3,
            strength: 5,
            damage: () => 1,
        },
        {
            name: 'Sniper Hyperfrag Round (seargeant buffs)',
            type: 'Heavy',
            numberOfShotsLabel: 'd3 (x2)',
            tags: ['multiprofile', 'bolter'],
            uniqueIdentifier: 'sniper',
            numberOfShots: () => d3() + d3(),
            AP: 0,
            plusToHit: 1,
            plusToWound: 1,
            strength: 5,
            damage: () => 1,
        },
        {
            name: 'Sniper Mortis Round (seargeant buffs)',
            type: 'Heavy',
            numberOfShotsLabel: '2',
            tags: ['multiprofile', 'bolter', 'mortal wound on 6+s to wound'],
            uniqueIdentifier: 'sniper',
            numberOfShots: () => 2,
            AP: 2,
            strength: 5,
            plusToWound: 1,
            plusToHit: 1,
            damage: () => d3(),
        },
        {
            name: 'Las Fusils',
            type: 'Heavy',
            numberOfShotsLabel: '1 (x3)',
            tags: ['multiprofile'],
            uniqueIdentifier: 'sniper',
            numberOfShots: () => 3,
            AP: 3,
            strength: 8,
            damage: () => 3,
        },
        {
            name: 'Las Fusils (seargeant buffs)',
            type: 'Heavy',
            numberOfShotsLabel: '1 (x2)',
            tags: ['multiprofile'],
            uniqueIdentifier: 'sniper',
            numberOfShots: () => 2,
            AP: 3,
            strength: 8,
            plusToHit: 1,
            plusToWound: 1,
            damage: () => 3,
        },
    ]
};
